
<div class="subpageSectionOne">
<div class="subpageSectionOneInside">
<h2 class="Oswald">The Hard Facts</h2>



<p class="subText">Atollogy leverages sensors, computer vision and artificial intelligence to improve gate turns efficiency and safety. Atollogy allows you to run your gate operations not only easier, but with more confidence.
</p>



<div class="productsTable">
  <div class="productsCol1 productsCell">
    
      <h2>The Problem</h2>
        <p>The current manual processes of tracking ground operations activities around the plane are slow, incomplete, and unreliable. Checklist-based systems are unable to precisely track all activities around the gate and human entry into any system is prone to error.</p>

<p>Frequently, managers cannot figure out which vehicle is in the tarmac and at what location without checking with multiple people using walkie talkies or other similar technologies. In fact, they don’t have accurate or up to date data captured automatically which requires them to run around the different gates to really understand the operational reality.</p>

<p>In summary, managers have resorted to management by wandering around (MBWA).  Most spend their time fighting fires in situations such as flight delays and have zero time to identify opportunities for productivity improvement.</p>

    
  </div>  
  <div class="productsCol2">
    <div class="productsCell">

        <div class="detail">
          <div class="productsCol_left">
            <h2>The Solution</h2>
            <p>Automate your entire ground operation with real time digital feedback, gathered automatically and displayed simultaneously.</p>

<p>This visual stream of data is actionable intelligence delivered to your operational team the moment it’s captured, allowing them to immediately identify and resolve any issue on the spot</p>

<p>Actionable intelligence = increased productivity!</p>
          </div>
          
        </div>
      
    </div>
    <div class="productsCell">
      
        <div class="detail">
        <div class="fullWidthBadge">
          <img src="<?php echo get_template_directory_uri(); ?>/images/products/ground-operations-management-Badge.png" >
        </div>  
          
        </div>
      
    </div>
  </div>  
</div>

<h2 class="Oswald">A (Much) Better Way</h2>
<p class="productsP">Atollogy was founded to give everyone real-time reporting on critical activities and events in their tarmac. With Atollogy, decision makers are fed actionable intelligence in real time, enabling them to take immediate action to correct an operational issue and get back full productivity.</p>




</div>

</div>



<div class="subpageSectionOne gray">
<div class="subpageSectionOneInside">

<h2 class="Oswald">HOW ATOLLOGY WORKS:</h2>

<!-- <img class="bigIcon1" src="<?php echo get_template_directory_uri(); ?>/images/industries/BigIcon1.svg"> -->


<div class="subpageTable">
<img src="<?php echo get_template_directory_uri(); ?>/images/industries/BigIcon2.svg">
<br><br>
<div class="subpageCell">
<h3>1 <span>Instrument</span></h3>
Non-invasive sensors and Atollogy Outriggers are rapidly installed. No retrofit necessary and it’s adaptable to any vintage machine.
</div>
<div class="subpageCell">
<h3>2 <span>Analyze</span></h3>

Atollogy captures the data to our cloud, feeds the artificial intelligence pipeline, and translates your physical operations into analytical data.
</div>
<div class="subpageCell">
<h3>3 <span>Action</span></h3>

Atollogy delivers real time feedback of actionable intelligence to understand and act upon.
</div>
<div class="clear"></div>
</div>

</div>
</div>

<div class="subpageSectionOne">
<div class="subpageSectionOneInside">

<h2 class="Oswald">GROUND OPERATIONS SOLUTION</h2>
<p class="productsPblueBig" style="font-size:18px;">Atollogy’s Ground Operations Management gives you the full picture - by measuring both machines and equipment (utilization) & people (efficiency), true productivity is captured for the first time.</p>

<h3>Atollogy can deliver:</h3>
<ul>

<li>True time from arrival to servicing for each turn</li>
<li>Average turnaround time by gate</li>
<li>Actual timestamp and evidence shareable across stakeholders</li>
<li>Time travel view to any potential incident that affect a gate turn</li>
<li>True duration of servicing vehicles working vs. idle</li>
<li>Insights into turnaround bottlenecks</li>
</ul>

</div>
</div>
<div class="subpageSectionOne gray">
<div class="subpageSectionOneInside" style="text-align:center;">
<!--
<div class="tableP">
<div class="cellP">
<h2 class="Oswald">VEHICLE MONITORING:</h2>

</div>
<div class="cellP">
<p class="productsPblueBig">Cycle Times, Weights & Trips/Day</p>
Composite Analytics generated by these measurements give supervisors and operators a view of current operational status driving real time actions and responses.
</div>
</div>
<br>
<br>

<p class="productsPblueBig">Atollogy’s Yard Operations Solution gives you the full picture - by measuring both machines and equipment (utilization) & people (efficiency), true productivity is captured for the first time.</p>
<br>
<br>

<h3>Atollogy can deliver:</h3>
<br>

<div class="tableP">
<div class="cellP">
<ul>
	<li>Average truck cycle time inside facility</li>
	<li>Truck entrance and exit times including truck identification</li>
	<li>Actual visit time stamps sharable with your customers.</li>
</ul>
</div>
<div class="cellP">
<ul>
<li>Duration trucks wait to be unloaded after arrival</li>
<li>Duration a loading dock was inactive while trucks were waiting in the yard</li>
<li>Actual weights of truck loads and real time alters when trucks are overloaded</li>
</ul>
</div>
</div>
-->
<br>
<br>
<img src="<?php echo get_template_directory_uri(); ?>/images/products/ground-operations-management-Screenshot1.png">
<br>
<br>

</div>
</div>

<div class="subpageSectionOne">
<div class="subpageSectionOneInside">

<h2 class="Oswald">GET STARTED WITHOUT DOWNTIME:</h2>

<!-- <img class="bigIcon1" src="<?php echo get_template_directory_uri(); ?>/images/industries/BigIcon1.svg"> -->
<p class="productsP">Atollogy’s sensor devices can be installed in minutes without the need for IT support, changes to existing processes, or downtime. Based on a few simple questions, we’ll begin learning about your operations and concentrate on your known weaknesses. As soon as the first week, you’ll be seeing new operational insights</p>

<!-- <ul style="margin:50px 0;">
<li>The sensors watch and learn how to visually identify movement in the yard</li>
<li>Computer vision tracks movement of vehicles in and out of the yard</li>
<li>Sensors monitor equipment status without costly hardware or interfaces</li>
<li>Outriggers connect automatically to manufacturing cloud to feed AI processes</li>
<li>Actionable insights are delivered via situational composite analytics
</ul>
 -->
<div class="productsTryItNow">
<div class="tableP">
<div class="cellP leftP">
<img src="<?php echo get_template_directory_uri(); ?>/images/products/ground-operations-management-BadgeBottom.png" >
</div>
<div class="cellP rightP">
<a href="<?php echo home_url(); ?>/#contact"><h2 class="Oswald">TRY IT NOW</h2></a>
<p>Empower your team to make real-time, informed decisions that decrease cycle time and increase margins without retrofit, disruptions to yard operations, or the need for expensive new machinery or IT infrastructure. Atollogy’s Yard Operations Solution democratizes enterprise-level IIoT and AI technologies to deliver true, “always on” visibility into operations with rapid time-to-value.</p>
<!-- <p>Ready to see a 10% productivity improvement? Contact us today.</p>
<p>650-382-0065</p>
 --></div>
</div>
</div>
</div>
</div>


</div>