<div class="section otherPages">
<div class="inside">
<h2>Atollogy Website Terms of Service</h2>

<!-- CONTENT -->

<p>Welcome to Atollogy.com (the &ldquo;<strong><em>Site</em></strong>&rdquo;). This Site includes all pages of Atollogy.com and any associated mobile websites, email notifications and correspondence and other informational sites owned and operated by Atollogy, Inc. These Terms of Service together with any documents expressly incorporated by reference (collectively, the &ldquo;<strong><em>Agreement</em></strong>&rdquo;) constitute a legal agreement between Atollogy, Inc. (&ldquo;<strong><em>Atollogy</em></strong>&rdquo;, &ldquo;<strong><em>we</em></strong>&rdquo;, &ldquo;<strong><em>our</em></strong>,&rdquo; or &ldquo;<strong><em>us</em></strong>&rdquo;) and you as the user or visitor of the Site (&ldquo;<strong><em>you</em></strong>&rdquo;) and apply to your use of the Site. Atollogy may offer certain product and/or services to customers for a fee or for evaluation purposes. In those situations, or when accessing Atollogy products or services through a link from the Site, additional Atollogy terms or requirements will apply to the use of such products and/or services. In the event of any conflict between such additional terms and this Agreement, the additional terms control.</p>
<p><strong>By accessing the Site, you hereby acknowledge that you have read and understood this Agreement and agree to be bound by the terms and conditions stated herein.</strong> <strong>You acknowledge and agree that we may revise and update this Agreement from time to time; all changes or updates to the Agreement are effective immediately when posted and will apply to your access to and use of the Site.</strong><strong> <em><u>If you do not agree to be bound by the terms of this Agreement, you must not access or use the Site</u>.</em></strong></p>
<ol>
<li><strong>Eligibility for Use</strong>. By using and accessing the Site, you state that you (a) are at least 18 years old or, if you are under the age of 18, that you have the permission of an adult who is deemed the user of the Site and assumes your responsibilities, (b) have the right, authority and capacity to enter into this Agreement, and abide by the terms and conditions of this Agreement, (c) are legally entitled to enter into this Agreement, and (d) are not prohibited by law from accessing or using the Site. If you cannot state that the foregoing are true, you may not use or access the Site or purchase any services provided by Atollogy. Without limiting the foregoing, the Site is not available to anyone under the age of 14 and if you are under the age of 14, you may not use the Site under any circumstances or for any reason. You agree to immediately notify Atollogy of any change in your eligibility to use the Site. We may change the eligibility requirements for the Site at any time or refuse to offer the Site to any person or entity.</li>
</ol>
<ol start="2">
<li><strong>Service Rules</strong>. Without limiting any of the terms and conditions stated herein, as a condition of your access to and use of the Site, you agree that: (a) you will only use the Site for lawful purposes; (b) you will not use the Site for any purpose that is prohibited by this Agreement; (c) you are responsible for all of your activity in connection with the Site; (d) you will not use the Site to cause nuisance, annoyance or inconvenience; (e) you will not try to harm the Site in any way whatsoever; (f) you will only use the Site for your own use and will not resell your account to a third party; (g) you will not attempt to bypass, circumvent or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Site; (h) you will not run any form of auto-responder or &ldquo;spam&rdquo; on the Site, use manual or automated software, devices, or other processes to &ldquo;crawl&rdquo; or &ldquo;spider&rdquo; any page of the Site, or harvest or scrape any content from the Site.</li>
</ol>
<p></p>
<ol start="3">
<li><strong>Privacy and Security</strong>. We collect three basic types of information and data: personal information (email, name, phone number), non-personal information, and aggregate data. We care about the privacy of our users. You understand that by using the Site and our services you consent to the collection, use and disclosure of your personally identifiable information and aggregate data as set forth in our <em>Privacy Policy</em>, and to have your personally identifiable information collected, used, transferred to and processed in the United States. We care about the integrity and security of your personal information, however, you understand and agree that we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk and as further described in our <em>Privacy Policy</em>.</li>
</ol>
<ol start="4">
<li><strong>Intellectual Property Rights</strong>.</li>
</ol>
<ul>
<li><u>Our Intellectual Property Rights to the Site</u>. The Site and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof) and any services (including software as a service services) are owned by Atollogy, its licensors or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. If you wish to make any use of material on our Site other than that set out in this section, please contact us at <a href="mailto:info@Atollogy.com">Info@Atollogy.com</a>. This Agreement permits you to use the for your personal, non-commercial use only. We grant you a limited, non-exclusive, non-transferable license: (i) use the Site, (ii) to view, download and print any content on the Site solely for your personal, non-commercial purposes; and (iii) to view any content on the Site to which you are permitted access solely for your personal, non-commercial purposes, and solely as permitted by the features of the Site. You have no right to sublicense the license rights granted in this section. You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Site or its content except as expressly permitted in this Agreement. If you breach the terms of this Section we may, in our sole discretion, deactivate your account or cease to allow you access to the Site. No right, title or interest in or to the Site, the Service or any content on the Site is transferred to you, and all rights not expressly granted are reserved by Atollogy.</li>
</ul>
<ul>
<li><u>Feedback</u>. You may from time to time provide, or be asked to provide, suggestions, comments or other feedback with respect to the Site and/or the services we provide to you (&ldquo;<strong>Feedback</strong>&rdquo;). Both parties agree that all Feedback is and shall be given entirely voluntarily. Feedback, even if designated as confidential by the party offering the Feedback, shall not be deemed to constitute confidential information or to impose any confidentiality or privacy obligations on Atollogy. We shall be free to use, disclose, publish, display, reproduce, license or otherwise distribute and fully exploit any Feedback entirely without obligation or restriction of any kind on account of intellectual property rights or otherwise.</li>
</ul>
<ul>
<li><u>Trademarks</u>. Atollogy&rsquo;s name, logo and all related names, logos, product and service names, designs and slogans, as well as the mark, &ldquo;ConsumerPrise&rdquo; are our trademarks. You may not use such marks without our prior written permission. All other names, logos, product and service names, designs and slogans on this Website are the trademarks of their respective owners.</li>
</ul>
<ol start="5">
<li><strong>Linking to the Website</strong>. You may not frame our homepage without our prior, written consent, however, you may link to our homepage without our consent provided that such link is not used in a context or in or around content that would in any way harm Atollogy&rsquo;s business or reputation, which Atollogy will determine in its sole discretion. If any link to our homepage violates the foregoing sentence, we will have the right to request that you remove such link and you shall immediately comply with such request. We also reserve the right to withdraw linking permission without notice and may disable all or any links at any time without notice in our discretion. You agree to cooperate with us in causing any unauthorized framing or linking immediately to cease.</li>
</ol>
<ol start="6">
<li><strong>Links from the Website</strong>. If the Site contains links to other sites and resources provided by third parties, these links are provided for your convenience only. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third party websites linked to this Site, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</li>
</ol>
<p></p>
<ol start="7">
<li><strong>Termination</strong>. If you wish to terminate this Agreement, you may do so by ceasing use of the Site, provided that you may not terminate any separate license agreement entered into with Atollogy by merely ceasing use of the Site. Atollogy may terminate this Agreement and your right to access the Site without notice if you breach any of the terms of this Agreement. All provisions of this Agreement, which by their nature should survive termination, shall survive termination, including, without limitation, licenses of Feedback, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</li>
</ol>
<p></p>
<ol start="8">
<li><strong>Disclaimer of Warranties</strong>. You understand that we cannot and do not guarantee or warrant that the Site will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE SITE OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SITE OR ON ANY WEBSITE LINKED TO IT. THE SITE, ITS CONTENT AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE SITE ARE USED AT YOUR OWN RISK AND ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER ATOLLOGY NOR ANY PERSON ASSOCIATED WITH US MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY OR AVAILABILITY OF THE SITE OR THAT ANY SERVICES OR ITEMS OBTAINED THROUGH THE SITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS. WE HEREBY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</li>
</ol>
<ol start="9">
<li><strong>Limitation on Liability</strong>. IN NO EVENT WILL ATOLLOGY, ITS AFFILIATES OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE SITE OR SUCH OTHER WEBSITES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SITE OR SUCH OTHER WEBSITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE. THE FOREGOING DOES NOT AFFECT ANY LIABILITY WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW AND SHALL APPLY NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.</li>
</ol>
<ol start="10">
<li><strong>Indemnification</strong>. You agree to defend, indemnify and hold Atollogy its affiliates, licensors and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors and assigns harmless, from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys' fees) arising out of or relating to your violation of this Agreement or your use of the Site, including, any use of the Site's content, services and products other than as expressly authorized in this Agreement.</li>
</ol>
<ol start="11">
<li><strong>Export Law Compliance</strong>. Use of the Site may be subject to laws of the United States and other countries. You agree to comply with all applicable export and import laws and regulations in connection with your use of the Site.</li>
</ol>
<ol start="12">
<li><strong>Auxiliary Services</strong>. Use of the Site requires Internet access through your computer or mobile device. You are responsible for all mobile carrier charges resulting from your use of the Site, including from any notifications provided by Atollogy in connection with your use of the Site and purchase and use of Dining Experiences. We do not guarantee that the Site will be compatible with all devices or will be supported by all mobile carriers. OUR SITE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS; WE ARE NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.</li>
</ol>
<p></p>
<ol start="13">
<li><strong>General Terms</strong>. All matters relating to the Site and this Agreement and any dispute or claim arising therefrom or related thereto, shall be governed by and construed in accordance with the internal laws of the State of Delaware without giving effect to any choice or conflict of law provision or rule. Any legal suit, action or proceeding arising out of, or related to, these Agreement or the Site shall be instituted exclusively in the federal courts of the United States in the or the courts of the State of Delaware in each case located in Newcastle County, Delaware. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts. You may not assign, delegate or transfer this Agreement or your rights or obligations hereunder without written consent from us. We may transfer, assign, or delegate this Agreement and any of our rights and obligations without consent. The section and paragraph headings in this Agreement are for convenience only and shall not affect their interpretation. No waiver by either party of any term or condition set forth in this Agreement shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of a party to assert a right or provision under this Agreement shall not constitute a waiver of such right or provision. If any provision of this Agreement is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Agreement will continue in full force and effect. We may give you notice by means of a general notice on or through the Site, electronic mail to your email address on record, or by written communication sent by first class mail or pre-paid post to your address on record for. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to Atollogy (such notice shall be deemed given when received by Atollogy) at any time by sending a letter, delivered by nationally recognized overnight delivery service or first class postage prepaid mail, to Atollogy at the following address: 1650 Coleman Avenue, Santa Clara, CA 95050, United States.</li>
</ol>
<p></p>
<p>The Agreement and our Privacy Policy constitute the sole and entire agreement between you and Atollogy with respect to the Site and supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Site.</p>
<p>This website is operated by Atollogy, Inc. Thank you for visiting! Please direct all feedback, comments, requests for technical support, and other communications relating to our Site to: <a href="mailto:info@Atollogy.com">Info@Atollogy.com</a>.</p></div>

<!-- END CONTENT -->

</div>